const $=id=>document.getElementById(id);let fleet=null,pending=null;
const ENDPOINTS={release:"/api/release-port",close:"/api/close-run",reopen:"/api/reopen-run"};
const esc=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'", "&#39;");
function render(data){fleet=data;$("synced").textContent=`SYNCED ${new Date(data.generated_at).toLocaleTimeString()}`;$("summary").innerHTML=Object.entries(data.counts).map(([k,v])=>`<article><span>${esc(k.toUpperCase())}</span><strong>${v}</strong></article>`).join("");$("decisions").classList.toggle("hidden",!data.decisions.length);$("decision-count").textContent=data.decisions.length;$("decision-list").innerHTML=data.decisions.map(d=>`<div class="decision"><strong>${esc(d.project)} - ${esc(d.label)}</strong><p>${esc(d.consequence)}</p></div>`).join("");$("projects").innerHTML=data.projects.map(project=>`<article class="project" data-state="${esc(project.state)}"><div class="project-top"><div><span class="badge">${esc(project.state)}</span><h3>${esc(project.name)} - ${esc(project.feature||"No active mission")}</h3><p>${esc(project.root)}</p></div><strong>${esc(project.progress??0)}% - ${esc(project.phase||"UNINITIALIZED")}</strong></div><div class="project-meta"><span>${esc(project.role||"NO ACTIVE ROLE")}</span><span>${esc(project.adapter||"-")}/${esc(project.model||"-")}</span><span>ENGINE ${esc(project.engine_version)}</span><span>${project.owner?`PORT ${esc(project.owner.port)} - ${esc(project.owner.health)}`:"NO OWNED PORT"}</span><span>${project.decisions.length} DECISION(S)</span></div><div class="project-actions">${project.dashboard_url?`<a href="${esc(project.dashboard_url)}" target="_blank" rel="noopener">OPEN DASHBOARD</a>`:`<span>${esc(project.dashboard_note)}</span>`}${project.owner?`<button data-op="release" data-root="${esc(project.root)}">RELEASE PORT</button>`:""}${project.state==="closed"&&project.run_closed?`<button data-op="reopen" data-root="${esc(project.root)}">REOPEN RUN</button>`:`<button class="danger" data-op="close" data-root="${esc(project.root)}">CLEANLY CLOSE RUN</button>`}</div></article>`).join("");document.querySelectorAll("[data-op]").forEach(b=>b.addEventListener("click",()=>openConfirm(b.dataset.op,b.dataset.root)));}
function openConfirm(op,root){const project=fleet.projects.find(p=>p.root===root);pending={op,project};const active=(project.sessions||[]).filter(s=>["launching","running"].includes(s.state));$("confirm-title").textContent=op==="release"?"Release owned dashboard port":op==="reopen"?"Reopen closed run":"Cleanly close run";$("confirm-context").textContent=[`Project: ${project.name}`,`Feature: ${project.feature||"none"}`,`State: ${project.state}`,`Owned port: ${project.owner?.port||"none"}`,`Managed sessions: ${active.map(s=>`${s.role}/${s.session_id}`).join(", ")||"none"}`,op==="close"?(active.length?"Effect: owned live sessions will be cancelled, audited, then owned ports released.":"Effect: closure is audited and owned ports are released."):op==="release"?"Effect: only the verified run-owned dashboard listener is stopped.":"Effect: workflow state reopens; durable history remains unchanged."].join("\n");$("reason-wrap").classList.toggle("hidden",op==="release");$("reason").value="";$("confirm").showModal();}
$("confirm").addEventListener("close",async()=>{if($("confirm").returnValue!=="default"||!pending)return;const {op,project}=pending;const reason=$("reason").value.trim();if(op!=="release"&&!reason){toast("Reason required");return;}const active=(project.sessions||[]).some(s=>["launching","running"].includes(s.state));try{const response=await fetch(ENDPOINTS[op],{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({root:project.root,binding:project.binding,confirm:true,reason:reason||null,cancel_active:active})});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);await refresh();}catch(error){toast(error.message);}finally{pending=null;}});
function toast(message){$("toast").textContent=message;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),5000)}
async function refresh(){try{const response=await fetch("/api/fleet",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);render(await response.json());}catch(error){toast(`Fleet telemetry interrupted: ${error.message}`)}}
refresh();const stream=new EventSource("/api/events");stream.addEventListener("fleet",event=>{render(JSON.parse(event.data));$("link").textContent="TACTICAL LINK: LIVE"});stream.onerror=()=>{$("link").textContent="TACTICAL LINK: RECONNECTING"};
